### ISSUE TITLE
Example Code does not run

### ISSUE THREAD

**Issue by makcuber** [iamthefox/luxafor#8]
I've installed the latest node LTS version and the api via npm, but when I run the example code I get this error: 

> device = new Luxafor(options);
                     ^
ReferenceError: options is not defined
    at Object.<anonymous> (C:\dev\js\luxaforTest.js:13:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

Which I tried to fix by changing 'options' to 'opts' to match the defination at the top of the example code. However, this then gives me this error:
> target = typeof target !== 'undefined' ? target : this.opts.defaults.setColor.target;
   ^
   TypeError: Cannot read property 'target' of undefined
    at Luxafor.setColor (C:\dev\node_modules\luxafor-api\src\luxafor.js:117:83)
    at Object.<anonymous> (C:\dev\js\luxaforTest.js:14:8)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

What am I missing?

**Comment by viktor42b** [comment]
Same here

**Comment by iamthefox** [comment]
This should not be an issue anymore.
